### ISSUE TITLE
issue with vgg initiating

### ISSUE THREAD

**Issue by VinceShieh** [fastai/courses#64]
I met an issue when initiating vgg
vgg = Vgg16()

not sure whether there is still such file on platform.ia

the backtrace:
/home/sparkuser/anaconda2/lib/python2.7/site-packages/h5py/_hl/files.pyc in make_fid(name, mode, userblock_size, fapl, fcpl, swmr)
     90         if swmr and swmr_support:
     91             flags |= h5f.ACC_SWMR_READ
---> 92         fid = h5f.open(name, flags, fapl=fapl)
     93     elif mode == 'r+':
     94         fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)

h5py/_objects.pyx in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/h5py_1486190692013/work/h5py/_objects.c:2856)()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/h5py_1486190692013/work/h5py/_objects.c:2814)()

h5py/h5f.pyx in h5py.h5f.open (/home/ilan/minonda/conda-bld/h5py_1486190692013/work/h5py/h5f.c:2102)()

IOError: Unable to open file (Truncated file: eof = 221519872, sblock->base_addr = 0, stored_eoa = 553482496)

**Comment by yanicklandry** [comment]
I solved this by doing :

```
rm /tmp/.keras/models/vgg16.h5
```

**Comment by adamheins** [comment]
I ran into this problem because I had accidentally terminated the download of the keras model data file before it was done, making it unreadable by h5py. I went into `.keras/models/` and deleted the data file so that keras would re-download it.

**Comment by monajalal** [comment]
for me after removing the model in $ ls ~/.keras/models I still get the same error 
```
 File "h5py/h5f.pyx", line 78, in h5py.h5f.open
OSError: Unable to open file (truncated file: eof = 98304, sblock->base_addr = 0, stored_eoa = 102853048)
```

**Comment by ALONSOlkp89** [comment]
@monajalal 
I had the same problem, did you solve it? Could you please share a little bit about your solution? Thanks.

**Comment by ALONSOlkp89** [comment]
@adamheins 
I couldn't find .keras/models/, there is no "models" under .keras, instead there is only such file: keras.json

**Comment by monajalal** [comment]
@ALONSOlkp89 so weird because when I moved from our cluster machine which had a P100 to my machine which has two 1080Ti, problem was solved. Both machines are running CentOS. Indeed, I didn't have to change anything and the resent_50.py keras code for transfer learning that detects Cifar10 objects ran just fine with no error.  https://github.com/fchollet/keras/issues/8546

**Comment by shashankhalo7** [comment]
I removed the vgg16.h5 from ~/.keras/models  (if the download was interrupted it will still be created we have to remove it ) and then manually downloaded the file and copied it to "~/.keras/models/". If there is no models folder create one. After that Vgg16() object  worked fine

**Comment by Abduoit** [comment]
Hi @shashankhalo7 

I did not find models folder under .keras I created one and I copied  vgg16.h5 file inside .keras/models

and still get the following error. any help please ???

```
Traceback (most recent call last):
  File "real_time.py", line 80, in <module>
    model.load_weights(TWO_MODEL_PATH, by_name=True)
  File "/home/jesse/gpu-py3/Mask_RCNN/model.py", line 2022, in load_weights
    f = h5py.File(filepath, mode='r')
  File "/home/jesse/gpu-py3/lib/python3.5/site-packages/h5py/_hl/files.py", line 269, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/home/jesse/gpu-py3/lib/python3.5/site-packages/h5py/_hl/files.py", line 99, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open
OSError: Unable to open file (truncated file: eof = 252575744, sblock->base_addr = 0, stored_eoa = 257557808)

```

**Comment by Waleed911** [comment]
Hello there,
I'm still having the same problem please any help???
I have Windows 10


This is the whole message I got : 
OSError                                   Traceback (most recent call last)
<ipython-input-9-3dcc53068365> in <module>()
----> 1 vgg16_model = keras.applications.vgg16.VGG16()

E:\Programs\Anaconda\envs\ztdl\lib\site-packages\keras\applications\vgg16.py in VGG16(include_top, weights, input_tensor, input_shape, pooling, classes)
    167                                     WEIGHTS_PATH_NO_TOP,
    168                                     cache_subdir='models')
--> 169         model.load_weights(weights_path)
    170         if K.backend() == 'theano':
    171             layer_utils.convert_all_kernels_in_model(model)

E:\Programs\Anaconda\envs\ztdl\lib\site-packages\keras\engine\topology.py in load_weights(self, filepath, by_name)
   2530         if h5py is None:
   2531             raise ImportError('`load_weights` requires h5py.')
-> 2532         f = h5py.File(filepath, mode='r')
   2533         if 'layer_names' not in f.attrs and 'model_weights' in f:
   2534             f = f['model_weights']

E:\Programs\Anaconda\envs\ztdl\lib\site-packages\h5py\_hl\files.py in __init__(self, name, mode, driver, libver, userblock_size, swmr, **kwds)
    269 
    270                 fapl = make_fapl(driver, libver, **kwds)
--> 271                 fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
    272 
    273                 if swmr_support:

E:\Programs\Anaconda\envs\ztdl\lib\site-packages\h5py\_hl\files.py in make_fid(name, mode, userblock_size, fapl, fcpl, swmr)
     99         if swmr and swmr_support:
    100             flags |= h5f.ACC_SWMR_READ
--> 101         fid = h5f.open(name, flags, fapl=fapl)
    102     elif mode == 'r+':
    103         fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)

h5py\_objects.pyx in h5py._objects.with_phil.wrapper()

h5py\_objects.pyx in h5py._objects.with_phil.wrapper()

h5py\h5f.pyx in h5py.h5f.open()

OSError: Unable to open file (Truncated file: eof = 238592000, sblock->base_addr = 0, stored_eof = 553467096)

**Comment by Waleed911** [comment]
I just solved my problem in Windows 10:
Go to this directory:
C:\Users\YOURNAME\.keras\models
Find the vgg16_weight(h5) file. So just delete it then run the python code again.
